project:
  title: "Análisis Estadístico del Titanic"
  type: default
  output-dir: docs

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true
    code-copy: true
    fig-width: 10
    fig-height: 6
    embed-resources: true
    self-contained: true
    error: true
    warning: true
    message: true

execute:
  freeze: false
  cache: true
  eval: true
  echo: true
  warning: true
  error: true
  include: true
  keep-md: false
  daemon: true
  cache-refresh: false
jupyter:
  kernels:
    - julia-1.11
preview:
  port: 5067
  browser: true
  watch:
    - "*.qmd"
    - "*.yml"
    - "*.yaml"
